services:
  - type: web
    name: code-execution-api
    env: python
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y nodejs npm g++ default-jdk && \
      npm install -g n && \
      n stable && \
      pip install -r requirements.txt
    startCommand: gunicorn execute.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false